# -*- coding: utf-8 -*-
"""bajajfinservaditi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqwgMNW_q_JlUminOcBTFuVnpldbG_BK
"""

pip install requests

import requests

import requests

name = "Aditi Sen"
reg_no = "0827AL221004"
email = "aditisen220540@acropolis.in"

generate_url = "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/PYTHON"
payload = {
    "name": name,
    "regNo": reg_no,
    "email": email
}

response = requests.post(generate_url, json=payload)

if response.status_code == 200:
    data = response.json()
    webhook_url = data.get("webhook")
    access_token = data.get("accessToken")

    print("Webhook and token received.")


    final_query = """
    SELECT
        e1.EMP_ID,
        e1.FIRST_NAME,
        e1.LAST_NAME,
        d.DEPARTMENT_NAME,
        COUNT(e2.EMP_ID) AS YOUNGER_EMPLOYEES_COUNT
    FROM EMPLOYEE e1
    JOIN DEPARTMENT d ON e1.DEPARTMENT = d.DEPARTMENT_ID
    LEFT JOIN EMPLOYEE e2
        ON e1.DEPARTMENT = e2.DEPARTMENT
        AND e2.DOB > e1.DOB
    GROUP BY
        e1.EMP_ID, e1.FIRST_NAME, e1.LAST_NAME, d.DEPARTMENT_NAME
    ORDER BY
        e1.EMP_ID DESC;
    """


    headers = {
        "Authorization": access_token,
        "Content-Type": "application/json"
    }
    body = {
        "finalQuery": final_query.strip()
    }

    result = requests.post(webhook_url, headers=headers, json=body)

    if result.status_code == 200:
        print(" SQL submitted successfully!")
    else:
        print(" Submission failed.")
        print(result.text)

else:
    print(" Failed to generate webhook.")
    print(response.text)

